table fact_qcchecks
	lineageTag: c98ec659-77ac-47cc-8c0d-a0923d766675

	column 'Compliance Status'
		dataType: string
		lineageTag: 4cdb1fc6-f763-4d7b-ac36-1a28cfd7227e
		summarizeBy: none
		sourceColumn: Compliance Status

		annotation SummarizationSetBy = Automatic

	column 'Deviation #'
		dataType: string
		lineageTag: 46614502-7c9a-412b-822c-48d484a3f336
		summarizeBy: none
		sourceColumn: Deviation #

		annotation SummarizationSetBy = Automatic

	column 'Finding Detection Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 40f984b2-263f-4f1a-9067-3979bfbd69f8
		summarizeBy: none
		sourceColumn: Finding Detection Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Medicinal Product Name'
		dataType: string
		lineageTag: 466aec00-f470-465c-8987-d3155af8a93b
		summarizeBy: none
		sourceColumn: Medicinal Product Name

		annotation SummarizationSetBy = Automatic

	column 'Check Status'
		dataType: string
		lineageTag: 85137ff6-f72e-46e7-b35e-20a093de012f
		summarizeBy: none
		sourceColumn: Check Status

		annotation SummarizationSetBy = Automatic

	column 'Record ID'
		dataType: string
		lineageTag: f1b5cb61-d5be-4678-b1ff-90b86a8d44d7
		summarizeBy: none
		sourceColumn: Record ID

		annotation SummarizationSetBy = Automatic

	column 'Check Name'
		dataType: string
		lineageTag: 61b81dfb-e9b8-4528-8149-49501ca5eed2
		summarizeBy: none
		sourceColumn: Check Name

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 36e2e755-dd9a-4d2e-a9b5-995e0eee053f
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'QC Name - Country'
		dataType: string
		lineageTag: 1560c5ba-ba09-418b-aa74-38119b553e41
		summarizeBy: none
		sourceColumn: QC Name - Country

		annotation SummarizationSetBy = Automatic

	column Search = fact_qcchecks[Check Name]&fact_qcchecks[Country]&fact_qcchecks[Medicinal Product Name]&fact_qcchecks[Deviation #]
		lineageTag: 267c5b2f-ca3b-450a-be41-15ed34dcb562
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Record Created Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 38087971-bf04-490e-821d-fb99797b6b2c
		summarizeBy: none
		sourceColumn: Record Created Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Right First Time' =
			
			if( fact_qcchecks[Check Status] = "No Finding",TRUE,FALSE)
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bd56bf05-0795-40f9-a4fc-2960990645c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Finding ID'
		dataType: string
		lineageTag: 8547b5bb-8bd7-4230-864f-18543854202e
		summarizeBy: none
		sourceColumn: Finding ID

	column 'Time to Resolve' =
			
			IF (
			    fact_qcchecks[Check Status] = "Finding Corrected",
			    DATEDIFF (
			        fact_qcchecks[Finding Detection Date],
			        fact_qcchecks[Finding Resolution Date],
			        DAY
			    ),
			    BLANK ()
			)
		formatString: 0
		lineageTag: f57d6b6f-0385-428e-9c99-79f020bfaa9a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"fact_qcchecks","TableItemName":"Time to Resolve (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Time to Resolve (bins)' =
			IF(
				ISBLANK('fact_qcchecks'[Time to Resolve]),
				BLANK(),
				INT('fact_qcchecks'[Time to Resolve] / 10) * 10
			)
		formatString: 0
		lineageTag: 380e8cee-8ba2-4a7a-af6c-c42c45401ac8
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "fact_qcchecks"
				          }
				        },
				        "Property": "Time to Resolve"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 10.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"fact_qcchecks"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Time to Resolve"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Time to Resolve"}},"Size":10.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Correction Target Date Met?' = ```
			
			
			VAR __Target = 
			SWITCH(
			    TRUE(),
			    RELATED(dim_process[Criticality]) = "Minor", 30,
			    RELATED(dim_process[Criticality]) = "Major", 45,
			    RELATED(dim_process[Criticality]) = "Critical", 60
			)
			
			RETURN
			
			IF(
			    fact_qcchecks[Time to Resolve] <= __Target,
			    TRUE,
			    FALSE
			)
			    
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dc8418c5-6b5d-4a36-b3ba-399af16fd3b4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Record Link' = "go to record →"
		lineageTag: 0fd63b6f-c27b-4071-b2f6-09ad5dea6b86
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Finding Resolution Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 3dc2854d-f3c9-4bd1-8bb0-f2b6b87135f5
		summarizeBy: none
		sourceColumn: Finding Resolution Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition fact_qcchecks = m
		mode: import
		source =
				let
				    Source = #"data export quality dashboard (fictional v2)",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Deviation #", "Finding Detection Date", "Finding Resolution Date", "Finding ID", "Medicinal Product Name", "Check Name", "Record ID", "Country", "Record Created Date"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Other Columns", "Check Status", each if [Finding Detection Date] = null then "No Finding" else if [Finding Resolution Date] = null and [Finding Detection Date] <> null then "Finding Detected" else "Finding Corrected"),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom1", "Compliance Status", each if [Check Status] = "Finding Detected" then "Non-Compliant" else "Compliant"),
				    #"Removed Duplicates" = Table.Distinct(#"Added Custom3"),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "QC Name - Country", each [Check Name]&" - "&[Country])
				in
				    #"Added Custom"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

